permalink: /:year/:month/:day/:title
debug: false
timezone: America/New_York

typekit: zal0bho
analytics:
  google: UA-33235804-1

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "skeleton"
      author: "Adrian Schaedle"
